# Generated by Django 3.2.4 on 2021-06-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_meeting_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='AloTradingPlatform',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Tradingview', 'Tradingview'), ('MT4/MT5', 'MT4/MT5'), ('Ninjatrader', 'Ninjatrader'), ('AmiBroker', 'AmiBroker'), ('Others', 'Others')], default='Python', max_length=128, null=True),
        ),
    ]
