# Generated by Django 3.2.4 on 2021-06-28 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210625_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='LanguageChoice',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='LanguageInput',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='Status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='slot',
            name='From',
            field=models.TimeField(choices=[(datetime.time(0, 0), '12:00 am'), (datetime.time(0, 30), '12:30 am'), (datetime.time(1, 0), '1:00 am'), (datetime.time(1, 30), '1:30 am'), (datetime.time(2, 0), '2:00 am'), (datetime.time(2, 30), '2:30 am'), (datetime.time(3, 0), '3:00 am'), (datetime.time(3, 30), '3:30 am'), (datetime.time(4, 0), '4:00 am'), (datetime.time(4, 30), '4:30 am'), (datetime.time(5, 0), '5:00 am'), (datetime.time(5, 30), '5:30 am'), (datetime.time(6, 0), '6:00 am'), (datetime.time(6, 30), '6:30 am'), (datetime.time(7, 0), '7:00 am'), (datetime.time(7, 30), '7:30 am'), (datetime.time(8, 0), '8:00 am'), (datetime.time(8, 30), '8:30 am'), (datetime.time(9, 0), '9:00 am'), (datetime.time(9, 30), '9:30 am'), (datetime.time(10, 0), '10:00 am'), (datetime.time(10, 30), '10:30 am'), (datetime.time(11, 0), '11:00 am'), (datetime.time(11, 30), '11:30 am'), (datetime.time(12, 0), '12:00 pm'), (datetime.time(12, 30), '12:30 pm'), (datetime.time(13, 0), '1:00 pm'), (datetime.time(13, 30), '1:30 pm'), (datetime.time(14, 0), '2:00 pm'), (datetime.time(14, 30), '2:30 pm'), (datetime.time(15, 0), '3:00 pm'), (datetime.time(15, 30), '3:30 pm'), (datetime.time(16, 0), '4:00 pm'), (datetime.time(16, 30), '4:30 pm'), (datetime.time(17, 0), '5:00 pm'), (datetime.time(17, 30), '5:30 pm'), (datetime.time(18, 0), '6:00 pm'), (datetime.time(18, 30), '6:30 pm'), (datetime.time(19, 0), '7:00 pm'), (datetime.time(19, 30), '7:30 pm'), (datetime.time(20, 0), '8:00 pm'), (datetime.time(20, 30), '8:30 pm'), (datetime.time(21, 0), '9:00 pm'), (datetime.time(21, 30), '9:30 pm'), (datetime.time(22, 0), '10:00 pm'), (datetime.time(22, 30), '10:30 pm'), (datetime.time(23, 0), '11:00 pm'), (datetime.time(23, 30), '11:30 pm')]),
        ),
        migrations.AlterField(
            model_name='slot',
            name='To',
            field=models.TimeField(choices=[(datetime.time(0, 0), '12:00 am'), (datetime.time(0, 30), '12:30 am'), (datetime.time(1, 0), '1:00 am'), (datetime.time(1, 30), '1:30 am'), (datetime.time(2, 0), '2:00 am'), (datetime.time(2, 30), '2:30 am'), (datetime.time(3, 0), '3:00 am'), (datetime.time(3, 30), '3:30 am'), (datetime.time(4, 0), '4:00 am'), (datetime.time(4, 30), '4:30 am'), (datetime.time(5, 0), '5:00 am'), (datetime.time(5, 30), '5:30 am'), (datetime.time(6, 0), '6:00 am'), (datetime.time(6, 30), '6:30 am'), (datetime.time(7, 0), '7:00 am'), (datetime.time(7, 30), '7:30 am'), (datetime.time(8, 0), '8:00 am'), (datetime.time(8, 30), '8:30 am'), (datetime.time(9, 0), '9:00 am'), (datetime.time(9, 30), '9:30 am'), (datetime.time(10, 0), '10:00 am'), (datetime.time(10, 30), '10:30 am'), (datetime.time(11, 0), '11:00 am'), (datetime.time(11, 30), '11:30 am'), (datetime.time(12, 0), '12:00 pm'), (datetime.time(12, 30), '12:30 pm'), (datetime.time(13, 0), '1:00 pm'), (datetime.time(13, 30), '1:30 pm'), (datetime.time(14, 0), '2:00 pm'), (datetime.time(14, 30), '2:30 pm'), (datetime.time(15, 0), '3:00 pm'), (datetime.time(15, 30), '3:30 pm'), (datetime.time(16, 0), '4:00 pm'), (datetime.time(16, 30), '4:30 pm'), (datetime.time(17, 0), '5:00 pm'), (datetime.time(17, 30), '5:30 pm'), (datetime.time(18, 0), '6:00 pm'), (datetime.time(18, 30), '6:30 pm'), (datetime.time(19, 0), '7:00 pm'), (datetime.time(19, 30), '7:30 pm'), (datetime.time(20, 0), '8:00 pm'), (datetime.time(20, 30), '8:30 pm'), (datetime.time(21, 0), '9:00 pm'), (datetime.time(21, 30), '9:30 pm'), (datetime.time(22, 0), '10:00 pm'), (datetime.time(22, 30), '10:30 pm'), (datetime.time(23, 0), '11:00 pm'), (datetime.time(23, 30), '11:30 pm')]),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
