# Generated by Django 3.2.4 on 2021-06-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210628_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutomerQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Name', max_length=256)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(default='Subject', max_length=1024)),
                ('Message', models.TextField(max_length=6000)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='PaymentLink',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='Link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Meeting Link'),
        ),
    ]
