# Generated by Django 3.2 on 2021-07-08 13:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210629_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UploaderName', models.CharField(max_length=126)),
                ('UploaderEmail', models.EmailField(max_length=254)),
                ('UploaderPhone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('StrategyName', models.CharField(max_length=300)),
                ('CapitalRequired', models.CharField(max_length=300)),
                ('Segment', models.CharField(choices=[('Equity', 'Equity'), ('Futures', 'Futures'), ('Options', 'Options'), ('Currency', 'Currency'), ('Commodity', 'Commodity'), ('Crypto', 'Cryptos')], max_length=300)),
                ('Price', models.PositiveIntegerField()),
                ('Image', models.FileField(upload_to='Images/')),
                ('Youtube', models.CharField(blank=True, max_length=300, null=True)),
                ('Website', models.CharField(blank=True, max_length=300, null=True)),
                ('Tradingview', models.CharField(blank=True, max_length=300, null=True)),
                ('Telegram', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customerqueries',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='day',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
